### ISSUE TITLE
Web gui not working

### ISSUE THREAD

**Issue by kekec777** [justanormaldev/ps4-pkg-sender#5]
This container was running fine , but somehow its not working anymore 
THe web gui is showing nothing at all

The error im getting is:
`01/02/2023 11:55:30 AM
TypeError: filesize is not a function
01/02/2023 11:55:30 AM
    at /opt/apps/pkg_sender/src/app.js:61:17
01/02/2023 11:55:30 AM
    at Array.forEach (<anonymous>)
01/02/2023 11:55:30 AM
    at walkSync (/opt/apps/pkg_sender/src/app.js:51:11)
01/02/2023 11:55:30 AM
    at /opt/apps/pkg_sender/src/app.js:55:20
01/02/2023 11:55:30 AM
    at Array.forEach (<anonymous>)
01/02/2023 11:55:30 AM
    at walkSync (/opt/apps/pkg_sender/src/app.js:51:11)
01/02/2023 11:55:30 AM
    at get_pkgs (/opt/apps/pkg_sender/src/app.js:67:10)
01/02/2023 11:55:30 AM
    at /opt/apps/pkg_sender/src/app.js:24:32
01/02/2023 11:55:30 AM
    at Layer.handle [as handle_request] (/opt/apps/pkg_sender/node_modules/express/lib/router/layer.js:95:5)
01/02/2023 11:55:30 AM
    at next (/opt/apps/pkg_sender/node_modules/express/lib/router/route.js:144:13)`

EDIT:
it seems the issue is:
size: filesize(stat.size)

and should be changed to :
size: (stat.size)

and i added this aswell (this is a little bit more readable / in mb):
size: (stat.size) / 1073741824 * 1024 

Please fix this issue :)

**Comment by yzhEric** [comment]
Hi, I have just encountered this issue and fixed it sucessfully. Show my solution here:
When the docker image was being built, I noticed:
```shell
npm WARN notsup Unsupported engine for filesize@10.1.4: wanted: {"node":">= 10.4.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
```
It means my Nodes.js's version is 8.17.0, which is lower than Node.js@10.4.0 for prerequisite of filesize@10.1.4.
So I try to use the old version of filesize: (remember this should be run in the container console)
```bash
npm install filesize@9.0.0
```
Restart the app and then it work!

**Comment by laleeroy** [comment]
> Hi, I have just encountered this issue and fixed it sucessfully. Show my solution here: When the docker image was being built, I noticed:
> 
> ```shell
> npm WARN notsup Unsupported engine for filesize@10.1.4: wanted: {"node":">= 10.4.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
> ```
> 
> It means my Nodes.js's version is 8.17.0, which is lower than Node.js@10.4.0 for prerequisite of filesize@10.1.4. So I try to use the old version of filesize: (remember this should be run in the container console)
> 
> ```shell
> npm install filesize@9.0.0
> ```
> 
> Restart the app and then it work!

Hello, this tool is still working?

**Comment by kekec777** [comment]
> > Hi, I have just encountered this issue and fixed it sucessfully. Show my solution here: When the docker image was being built, I noticed:
> > ```shell
> > npm WARN notsup Unsupported engine for filesize@10.1.4: wanted: {"node":">= 10.4.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It means my Nodes.js's version is 8.17.0, which is lower than Node.js@10.4.0 for prerequisite of filesize@10.1.4. So I try to use the old version of filesize: (remember this should be run in the container console)
> > ```shell
> > npm install filesize@9.0.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Restart the app and then it work!
> 
> Hello, this tool is still working?

Yeah it does...

**Comment by kekec777** [comment]
> > Hi, I have just encountered this issue and fixed it sucessfully. Show my solution here: When the docker image was being built, I noticed:
> > ```shell
> > npm WARN notsup Unsupported engine for filesize@10.1.4: wanted: {"node":">= 10.4.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It means my Nodes.js's version is 8.17.0, which is lower than Node.js@10.4.0 for prerequisite of filesize@10.1.4. So I try to use the old version of filesize: (remember this should be run in the container console)
> > ```shell
> > npm install filesize@9.0.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Restart the app and then it work!
> 
> Hello, this tool is still working?

Yes this is working

**Comment by laleeroy** [comment]
> > > Hi, I have just encountered this issue and fixed it sucessfully. Show my solution here: When the docker image was being built, I noticed:
> > > ```shell
> > > npm WARN notsup Unsupported engine for filesize@10.1.4: wanted: {"node":">= 10.4.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > It means my Nodes.js's version is 8.17.0, which is lower than Node.js@10.4.0 for prerequisite of filesize@10.1.4. So I try to use the old version of filesize: (remember this should be run in the container console)
> > > ```shell
> > > npm install filesize@9.0.0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Restart the app and then it work!
> > 
> > 
> > Hello, this tool is still working?
> 
> Yeah it does...

I tried to use it on arm64 device (raspberrypi 5) but it is showing nothing on my browser, will try your fix later

**Comment by laleeroy** [comment]
Still not showing nothing, is this commit right?

https://github.com/laleeroy/ps4-pkg-sender/commit/84eb67f901ed4ef1c691a01b323e580ad9bcd71f

Logs

Fri, 06 Sep 2024 04:53:57 GMT express:application set "x-powered-by" to true
Fri, 06 Sep 2024 04:53:57 GMT express:application set "etag" to 'weak'
Fri, 06 Sep 2024 04:53:57 GMT express:application set "etag fn" to [Function: generateETag]
Fri, 06 Sep 2024 04:53:57 GMT express:application set "env" to 'development'
Fri, 06 Sep 2024 04:53:57 GMT express:application set "query parser" to 'extended'
Fri, 06 Sep 2024 04:53:57 GMT express:application set "query parser fn" to [Function: parseExtendedQueryString]
Fri, 06 Sep 2024 04:53:57 GMT express:application set "subdomain offset" to 2
Fri, 06 Sep 2024 04:53:57 GMT express:application set "trust proxy" to false
Fri, 06 Sep 2024 04:53:57 GMT express:application set "trust proxy fn" to [Function: trustNone]
Fri, 06 Sep 2024 04:53:57 GMT express:application booting in development mode
Fri, 06 Sep 2024 04:53:57 GMT express:application set "view" to [Function: View]
Fri, 06 Sep 2024 04:53:57 GMT express:application set "views" to '/opt/apps/pkg_sender/views'
Fri, 06 Sep 2024 04:53:57 GMT express:application set "jsonp callback name" to 'callback'
Fri, 06 Sep 2024 04:53:57 GMT express:router use '/' query
Fri, 06 Sep 2024 04:53:57 GMT express:router:layer new '/'
Fri, 06 Sep 2024 04:53:57 GMT express:router use '/' expressInit
Fri, 06 Sep 2024 04:53:57 GMT express:router:layer new '/'
Fri, 06 Sep 2024 04:53:57 GMT express:router use '/' logger
Fri, 06 Sep 2024 04:53:57 GMT express:router:layer new '/'
Fri, 06 Sep 2024 04:53:57 GMT body-parser deprecated undefined extended: provide extended option at src/app.js:17:17
Fri, 06 Sep 2024 04:53:57 GMT express:router use '/' urlencodedParser
Fri, 06 Sep 2024 04:53:57 GMT express:router:layer new '/'
Fri, 06 Sep 2024 04:53:57 GMT express:application set "view engine" to 'html'
Fri, 06 Sep 2024 04:53:57 GMT express:application set "views" to '/opt/apps/pkg_sender/src/views'
Fri, 06 Sep 2024 04:53:57 GMT express:router:route new '/'
Fri, 06 Sep 2024 04:53:57 GMT express:router:layer new '/'
Fri, 06 Sep 2024 04:53:57 GMT express:router:route get '/'
Fri, 06 Sep 2024 04:53:57 GMT express:router:layer new '/'
Fri, 06 Sep 2024 04:53:57 GMT express:router:route new '/install'
Fri, 06 Sep 2024 04:53:57 GMT express:router:layer new '/install'
Fri, 06 Sep 2024 04:53:57 GMT express:router:route post '/install'
Fri, 06 Sep 2024 04:53:57 GMT express:router:layer new '/'
PS4 PKG sender listening on port 8033 serving files from /opt/apps/pkg_sender/files
Fri, 06 Sep 2024 04:54:41 GMT express:router dispatching GET /
Fri, 06 Sep 2024 04:54:41 GMT express:router query  : /
Fri, 06 Sep 2024 04:54:41 GMT express:router expressInit  : /
Fri, 06 Sep 2024 04:54:41 GMT express:router logger  : /
Fri, 06 Sep 2024 04:54:41 GMT express:router urlencodedParser  : /
Fri, 06 Sep 2024 04:54:41 GMT express:view lookup "index.html"
Fri, 06 Sep 2024 04:54:41 GMT express:view stat "/opt/apps/pkg_sender/src/views/index.html"
Fri, 06 Sep 2024 04:54:41 GMT express:view render "/opt/apps/pkg_sender/src/views/index.html"
::ffff:100.71.103.81 - - [06/Sep/2024:04:54:41 +0000] "GET / HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
Fri, 06 Sep 2024 04:54:43 GMT express:router dispatching GET /
Fri, 06 Sep 2024 04:54:43 GMT express:router query  : /
Fri, 06 Sep 2024 04:54:43 GMT express:router expressInit  : /
Fri, 06 Sep 2024 04:54:43 GMT express:router logger  : /
Fri, 06 Sep 2024 04:54:43 GMT express:router urlencodedParser  : /
Fri, 06 Sep 2024 04:54:43 GMT express:view lookup "index.html"
Fri, 06 Sep 2024 04:54:43 GMT express:view stat "/opt/apps/pkg_sender/src/views/index.html"
Fri, 06 Sep 2024 04:54:43 GMT express:view render "/opt/apps/pkg_sender/src/views/index.html"
::ffff:100.71.103.81 - - [06/Sep/2024:04:54:43 +0000] "GET / HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
Fri, 06 Sep 2024 04:54:49 GMT express:router dispatching GET /
Fri, 06 Sep 2024 04:54:49 GMT express:router query  : /
Fri, 06 Sep 2024 04:54:49 GMT express:router expressInit  : /
Fri, 06 Sep 2024 04:54:49 GMT express:router logger  : /
Fri, 06 Sep 2024 04:54:49 GMT express:router urlencodedParser  : /
Fri, 06 Sep 2024 04:54:49 GMT express:view lookup "index.html"
Fri, 06 Sep 2024 04:54:49 GMT express:view stat "/opt/apps/pkg_sender/src/views/index.html"
Fri, 06 Sep 2024 04:54:49 GMT express:view render "/opt/apps/pkg_sender/src/views/index.html"
::ffff:100.71.103.81 - - [06/Sep/2024:04:54:49 +0000] "GET / HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"

**Comment by kekec777** [comment]
![Screenshot 2024-09-06 083338](https://github.com/user-attachments/assets/8f3b3daf-7e9d-4d00-82f4-85c0e015c230)
![Screenshot 2024-09-06 083717](https://github.com/user-attachments/assets/0b2f251b-5ec4-4492-9e18-da8744ddaed2)

Mine is working fine on a Debian 11 (OMV 6.9.16-1 (Shaitan)) -  Docker version 27.2.0, build 3ab4256
And as you can see i have tweaked a little bit with the code , so i can update ip adr from webgui and the pictures is clickable so they get centered and bigger..

**Comment by laleeroy** [comment]
> ![Screenshot 2024-09-06 083338](https://private-user-images.githubusercontent.com/20354802/365058508-8f3b3daf-7e9d-4d00-82f4-85c0e015c230.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDUxNTAsIm5iZiI6MTcyNTYwNDg1MCwicGF0aCI6Ii8yMDM1NDgwMi8zNjUwNTg1MDgtOGYzYjNkYWYtN2U5ZC00ZDAwLTgyZjQtODVjMGUwMTVjMjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA2NDA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjYTYzMjg1ODgyMTZmZWU1NDhkYzY2NTJkNzMxZmU4NWU5MjY4ODNhMDczZjczMmU0MmVlMWI3NTNiYmZhZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ojJaAhlzilOxgj4MbRxi5jd8XbZgfvwbn7exJ5PONTA) ![Screenshot 2024-09-06 083717](https://private-user-images.githubusercontent.com/20354802/365059263-0b2f251b-5ec4-4492-9e18-da8744ddaed2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDUxNTAsIm5iZiI6MTcyNTYwNDg1MCwicGF0aCI6Ii8yMDM1NDgwMi8zNjUwNTkyNjMtMGIyZjI1MWItNWVjNC00NDkyLTllMTgtZGE4NzQ0ZGRhZWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA2NDA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3OTI0ZDdkY2YwZTQ1Yjk5MTM5Nzk5YzBkNGMxZTNmMjJiZmYwOGE3NzE3OGZhYmRhZjAwODNiNzNjNDc2MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UTemO0bhgLbOl-mew8t1V1y_DJftGIMV5cGuCUZMxw8)
> 
> Mine is working fine on a Debian 11 (OMV 6.9.16-1 (Shaitan)) - Docker version 27.2.0, build 3ab4256 And as you can see i have tweaked a little bit with the code , so i can update ip adr from webgui and the pictures is clickable so they get centered and bigger..

Hmmmm, I'll try again later with a pc browser.
Btw I don't have PS4 yet, but in this software, whats the highest firmware that it could work?

**Comment by kekec777** [comment]
This container doesnt care or known if you ps4 is jailbroken 
Its only purpose is to send pkg to the ip adr.
But the newest firmware that is jailbroken is :
PS4 11.00 Jailbreak – PPPwn (https://wololo.net/ps4-jailbreak-ps4-cfw4dummies/)
So you start Remote Package Installer (https://www.gamebrew.org/wiki/Remote_Package_Installer_PS4)
then you go into this container / webgui and send pkg.. 

Ill recomment you to watch some of these videoes in here:
https://www.youtube.com/@MODDEDWARFARE

**Comment by laleeroy** [comment]
> This container doesnt care or known if you ps4 is jailbroken Its only purpose is to send pkg to the ip adr. But the newest firmware that is jailbroken is : PS4 11.00 Jailbreak – PPPwn (https://wololo.net/ps4-jailbreak-ps4-cfw4dummies/) So you start Remote Package Installer (https://www.gamebrew.org/wiki/Remote_Package_Installer_PS4) then you go into this container / webgui and send pkg..
> 
> Ill recomment you to watch some of these videoes in here: https://www.youtube.com/@MODDEDWARFARE

Got it, thanks man!
